### ISSUE TITLE
rosbag topics about GNSS/INS

### ISSUE THREAD

**Issue by eros-ck** [weisongwen/UrbanLoco#11]
Thanks for the great work and sharing with the community.

I have some questions listed below:
- What are `/navsat/fix` and `/navsat/odom` in the rosbags? Are they from NovAtel or ublox?
- What is the difference `/imu_rt` and `/imu_raw`?

**Comment by weisongwen** [comment]
Thanks for your interest in our dataset. For the CA dataset, the ```/navsat/fix``` and ```/navsat/odom``` are the middle information which are combined in topic ```/novatel_data/inspvax``` for ground truth evaluation. The ```/imu_rt``` is the imu data from SPAN-CPT but the accuracy is not guaranteed. 

As mentioned on the readme page, the ```/imu_raw``` is the imu data from Xsens IMU.

**Comment by eros-ck** [comment]
Thank you @weisongwen. Appreciate it!
