### ISSUE TITLE
where is poor gnss data?

### ISSUE THREAD

**Issue by yuxu1997** [weisongwen/UrbanLoco#13]
hello, i've downloaded your HK Dataset. Thanks for your work. According to your introduction, HK-Data20190426-1、HK-Data20190316-2、HK-Data20190316-1 are with poor gnss visibilities. But i read gnss data with good quality from topic /navsat/fix, as shown in the second figure. I need raw gnss data with outliers or bad signals. So i want to ask if i chose the wrong topic and where can i get poor gnss data? Thank you.
![f](https://user-images.githubusercontent.com/47274016/103342119-a8712e80-4ac3-11eb-8ec7-434f1af7ad31.png)
![a](https://user-images.githubusercontent.com/47274016/103342131-aeffa600-4ac3-11eb-8c86-cf00972755d1.png)

**Comment by weisongwen** [comment]
Hi, Thanks for your interest. Sorry for the delay, we try our best to reply to the issues every several days,

We only provide the raw GNSS data via rostopic "/GNSS_" in the HK dataset. The data you use (/navsat/fix) is the ground truth pose from SPAN-CPT. 
1.  If you want to use raw GNSS data with poor GNSS measurements, you can refer to our team's other dataset here (https://github.com/weisongwen/UrbanNavDataset). 
2. BTW, you can also try the CA dataset directly using the GNSS loose solution via rostopic "/ublox_node/fix".

It can be good if you can present your issue in English which can be other users to track similar issues.

Thanks,

**Comment by weisongwen** [comment]
Closed, as no response for this issue.

**Comment by bryantaoli** [comment]
Thank you Dr.Wen, in Urbanloco website, the HK-Data20190426-1 cantains GNSS (RINEX) (GNSS Raw Data). But it cannot be clicked, could you please update it, thank you agian.


![image](https://user-images.githubusercontent.com/30526360/163561443-af03dc34-e014-4b4e-981c-cba508908317.png)

**Comment by weisongwen** [comment]
Solved and closed. Feel free to re-open if necessary,

**Comment by bryantaoli** [comment]
> Thank you Dr.Wen, in Urbanloco website, the HK-Data20190426-1 cantains GNSS (RINEX) (GNSS Raw Data). But it cannot be clicked, could you please upload it, thank you agian.
> 
> ![image](https://user-images.githubusercontent.com/30526360/163561443-af03dc34-e014-4b4e-981c-cba508908317.png)

Thank @weisongwen to provide the RINEX file of HK-Data20190426-1. 
I upload it below:
[RINEX-HKDate20190426-1.zip](https://github.com/weisongwen/UrbanLoco/files/8496055/RINEX-HKDate20190426-1.zip)
