### ISSUE TITLE
About ublox f9p

### ISSUE THREAD

**Issue by Hchu2** [weisongwen/UrbanLoco#14]
Thank you for your work on these data sets, I have a small question. I found that you will provide ublox f9p data later. How long will it take? Because m8t only has single-frequency GNSS data. Based on this,performing single-frequency dynamic PPP in such a complex urban environment may result in unsatisfactory results.Thanks.

**Comment by weisongwen** [comment]
Hi @Hchu2 , Thanks for your interest and sorry for the late reply. We try our best to maintain this repo but we are still overstretched. We will provide the F9P dataset in our UrbanNav dataset. https://github.com/IPNL-POLYU/UrbanNavDataset
