### ISSUE TITLE
how to obtain trajectory from span-cpt

### ISSUE THREAD

**Issue by kevin2431** [weisongwen/UrbanLoco#16]
Thanks for sharing the dataset. I want to evaluate my lidar odometry algorithm on this dataset but do not familiar with the GNSS sensor. I wonder if there is a library that can help me convert novatel_msgs/INSPVAX to 6DoF trajectory like the KITTI dataset.

**Comment by weisongwen** [comment]
Hi @kevin2431 , Thanks for your interest. You may need some functions to convert the latitude, longitude and altitude to the Eeast, North, Up frames. I have a piece of code that you may need as follows:

https://github.com/weisongwen/GraphGNSSLib/blob/main/global_fusion/include/gnss_tools.h#L220

Best,
Weisong,

**Comment by Saixiaoma** [comment]
> Hi @kevin2431 , Thanks for your interest. You may need some functions to convert the latitude, longitude and altitude to the Eeast, North, Up frames. I have a piece of code that you may need as follows:
> 
> https://github.com/weisongwen/GraphGNSSLib/blob/main/global_fusion/include/gnss_tools.h#L220
> 
> Best, Weisong,

Hi, how to obtain the rotation(yaw, pitch, roll) from the span-cpt?

**Comment by weisongwen** [comment]
you can get the orientation from the topic `/novatel_data/inspvax` which is the rostopic from the span-cpt.

**Comment by weisongwen** [comment]
Feel free to re-open if needed.

**Comment by wwtinwhu** [comment]
Hello, @weisongwen . I used function llh2ecef you provided to convert /novatel_data/bestpos to the xyz. The xy coordinate is similar as the fig which you provided in the README. While, the z values seems not right. I used HK-Data20190117.bag where the GNSS signal is good. Look for help.
