### ISSUE TITLE
How do I get the ring of robosense

### ISSUE THREAD

**Issue by pre-master** [weisongwen/UrbanLoco#17]
Thanks for sharing the dataset . In ca-dataset, your lidar is robosense-32，unlike VLP, the ring of robosense-32 is evenly distributed in the vertical direction according to the fixed resolution. So can you give me some advice on restoring the vertical column information of /rslidar_point in rostopic.(As shown in the figure below, how can I get the arrangement of a ring in the vertical direction)
![2021-12-29 11-54-41屏幕截图](https://user-images.githubusercontent.com/56384731/147626000-03c75234-2384-4277-9d3b-d26f11f4689d.png)

Look forward to your reply

**Comment by pre-master** [comment]
I solve it

**Comment by pytorch1100** [comment]
Hi@pre-master , I have the same problem. Could you tell me how to solve it?Looking forward to your reply!
