### ISSUE TITLE
How do I get the ring of robosense Lidar?

### ISSUE THREAD

**Issue by pytorch1100** [weisongwen/UrbanLoco#18]
Hi @weisongwen ,thank you for your great dataset!How do I get the ring of robosense Lidar?And convert to velodyne format?

**Comment by weisongwen** [comment]
Hey @pytorch1100 ! Thank you for your interest in this dataset. Unfortunately, the ring information seems to be not included in the collected data as the driver we used previously is too old. You may like to try our new dataset UrbanNav which includes the ring of the Velodyne LiDAR. https://github.com/IPNL-POLYU/UrbanNavDataset

Thank you,
Weisong,

**Comment by pytorch1100** [comment]
OK! Thank you for your reply! I will try the UrbanNav dataset.
