### ISSUE TITLE
Are the UrbanLoco Dataset provide GNSS RENIX File as UrbanNav

### ISSUE THREAD

**Issue by bryantaoli** [weisongwen/UrbanLoco#4]
Are the UrbanLoco Dataset provide GNSS RENIX File as UrbanNav which also collected by you at https://github.com/weisongwen/UrbanNavDataset, Thank you!

**Comment by weisongwen** [comment]
Hi @bryantaoli , thanks for your interest. We definitely provide the GNSS raw data but not in RINEX format.

Since this dataset is mainly for mapping and localization and we think researchers in the robotics field may not familiar with the GNSS RINEX files.  Therefore, we collect GNSS raw data using the u-blox driver (https://github.com/KumarRobotics/ublox). Please look into the message format which include the pseudo-range and carrier-phase measurements (https://github.com/KumarRobotics/ublox/tree/master/ublox_msgs/msg). 

Hope this help,
Weisong,

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by bryantaoli** [comment]
Thank you so much. So in my understanding, the GNSS raw data in rosbag can be turned into RINEX format?

**Comment by weisongwen** [comment]
@bryantaoli , I think you can directly have access to the pseudorange, etc, data from the rostopic. You can look into the link https://github.com/KumarRobotics/ublox. 

Thanks,
Weisong,

**Comment by bryantaoli** [comment]
> @bryantaoli , I think you can directly have access to the pseudorange, etc, data from the rostopic. You can look into the link https://github.com/KumarRobotics/ublox.
> 
> Thanks,
> Weisong,

But, if I want to use the rtklib to analyze and deal with the GNSS raw data, the GNSS raw data in rosbag should be converted to RINEX so that rtklib can solve it.

**Comment by weisongwen** [comment]
> > @bryantaoli , I think you can directly have access to the pseudorange, etc, data from the rostopic. You can look into the link https://github.com/KumarRobotics/ublox.
> > Thanks,
> > Weisong,
> 
> But, if I want to use the rtklib to analyze and deal with the GNSS raw data, the GNSS raw data in rosbag should be converted to RINEX so that rtklib can solve it.

Yes, the rostopic in the rosbag does not directly usable for RTKLIB. You may need to do some data post-processing to make it fit the RTKLIB you mentioned. 

Best,
Weisong,

**Comment by TakahashiJinxu** [comment]
@bryantaoli Hello! Have you found out how to covert the raw measurements to RINEX file? I have written a simple ROS package to convert them, named ublox2rinex. I tested it using two sequences in this dataset, and the single point positioning results look to be correct, although not accurate.  I have uploaded it onto my github. Should you are interested, you may have a look.  However, I am not sure about the frequency of the carrier, and I assumed them to be L1 band (maybe incorrect).  Welcome for instructions and suggestions!

**Comment by bryantaoli** [comment]
> @bryantaoli Hello! Have you found out how to covert the raw measurements to RINEX file? I have written a simple ROS package to convert them, named ublox2rinex. I tested it using two sequences in this dataset, and the single point positioning results look to be correct, although not accurate. I have uploaded it onto my github. Should you are interested, you may have a look. However, I am not sure about the frequency of the carrier, and I assumed them to be L1 band (maybe incorrect). Welcome for instructions and suggestions!

Of course, I am very interested in your work,  I gave you a star first and I will have some tests. Thank you very much to share your code.

**Comment by weisongwen** [comment]
@bryantaoli It can be great if you could let us know if it works. 
@TakahashiJinxu , if you agree, we can add a link to your nice package on our UrbanLoco Github page. 

Best,
Weisong,

**Comment by TakahashiJinxu** [comment]
> @TakahashiJinxu , if you agree, we can add a link to your nice package on our UrbanLoco Github page.

OK, that will be very good.

**Comment by bryantaoli** [comment]
> 
> 
> @bryantaoli It can be great if you could let us know if it works.
> @TakahashiJinxu , if you agree, we can add a link to your nice package on our UrbanLoco Github page.
> 
> Best,
> Weisong,

I have run @TakahashiJinxu 's code on HKData20190117  and get a RINEX File only containing GPS and GLONASS observation. I don't know if the data only contains two systems.  And I also found that the title of the RINEX File was wrong so that the rtkplot cannot plot the O file turning by @TakahashiJinxu. I show the result I get below:
1.rtkplotcannot plot the O file:
![图片](https://user-images.githubusercontent.com/30526360/92065261-f013d200-edd1-11ea-95eb-6adfb550d04a.png)
2.SPP result:
![图片](https://user-images.githubusercontent.com/30526360/92065304-0ae64680-edd2-11ea-98ed-95989849c588.png)

**Comment by weisongwen** [comment]
Hi @bryantaoli , Thanks for your update.

But you can get the results using RTKLIB, right? I am not sure what you mean by .o file. Do you mean the .pos file saving the results?

**Comment by bryantaoli** [comment]
> Hi @bryantaoli , Thanks for your update.
> 
> But you can get the results using RTKLIB, right? I am not sure what you mean by .o file. Do you mean the .pos file saving the results?

I am sorry to let you misunderstand, '.o file' is the observation file in RINEX format.   And it can be dealt with by RTKLIB. It is a very good job, but maybe have some small bugs on the head of RINEX.

**Comment by weisongwen** [comment]
@bryantaoli Well noted. I think the .obs file is the .o file you mentioned.

**Comment by bryantaoli** [comment]
> @bryantaoli Well noted. I think the .obs file is the .o file you mentioned.

Yes, you are right.

**Comment by TakahashiJinxu** [comment]
According to @bryantaoli, using my generated RINEX observation file one can get the SPP results using RTKLIB, but the rtkplot can't plot the observations. I will make some modifications later on.

**Comment by TakahashiJinxu** [comment]
Now according to me and @bryantaoli, my package has been free of bugs.

**Comment by weisongwen** [comment]
@TakahashiJinxu @bryantaoli  Thanks for your update, I will add a link to the Github page.

Best,
Weisong,

**Comment by weisongwen** [comment]
Solved and closed.
