### ISSUE TITLE
Downloading problem: Do HK-Data20190117 and HK-Data20190317 need to be shared using sharing link?

### ISSUE THREAD

**Issue by TakahashiJinxu** [weisongwen/UrbanLoco#6]
Hello! I have been trying to download the data, but failing every time I try to download HK-Data20190117 and HK-20190317. I can successfully start downloading other sequences. I examined the download links, and discovered that the links of  HK-Data20190117 and HK-20190317 do not end with "sharing". Are they private links so that I can't download? (I understand it may also due to my network problems.) Thank you!

**Comment by weisongwen** [comment]
@TakahashiJinxu  I think it is your network issues since I can download it in several computers from my end.

**Comment by TakahashiJinxu** [comment]
> @TakahashiJinxu I think it is your network issues since I can download it in several computers from my end.

Thank you! It may indeed due to my network issues.

**Comment by weisongwen** [comment]
@TakahashiJinxu . Thanks for your update

Closed and Fixed :-)
